default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: password
  host: localhost

development:
  <<: *default
  database: jobtracker_development

test:
  <<: *default
  database: jobtracker_test

production:
  <<: *default
  database: jobtracker_production
  username: jobtracker
  password: <%= ENV["JOBTRACKER_DATABASE_PASSWORD"] %>
